<a href="https://colab.research.google.com/github/shubham62025865/shubham1/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Create tensors

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
tf.__version__

'2.12.0'

In [ ]:
tf.constant([1,2,3,4])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
a = tf.Variable([1,2,3,4])

In [ ]:
a[1].assign(5).numpy()

array([1, 5, 3, 4], dtype=int32)

In [ ]:
a = tf.constant([1,2,3,4])
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
a = pd.Series([1,2,3,4])
a.values

array([1, 2, 3, 4])

In [ ]:
# tf.constant

In [ ]:
#tf.Variable
t = tf.Variable([[12,25,23,16],
                [10,9,5,7]])

In [ ]:
t[[1,2]]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
tf.constant([[12,25,23,16],
             [10,9,5,7]])

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[12, 25, 23, 16],
       [10,  9,  5,  7]], dtype=int32)>

In [ ]:
b = tf.constant([12,25,23,16,10,9,5,7], shape = (2,4))
b

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[12, 25, 23, 16],
       [10,  9,  5,  7]], dtype=int32)>

In [ ]:
b[:, 1:3]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 23],
       [ 9,  5]], dtype=int32)>

In [ ]:
b[1,2:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 7], dtype=int32)>

In [ ]:
at = tf.Variable([[125,25,23,16],
                  [45,56,89,235]])

In [ ]:
at

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[125,  25,  23,  16],
       [ 45,  56,  89, 235]], dtype=int32)>

To change an element of a tf.Variable() tensor requires the assign() method.

In [ ]:
a = tf.constant([1,2,3,4])
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
a[2].assign(54)

AttributeError: ignored

In [ ]:
t

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[12, 25, 23, 16],
       [10,  9,  5,  7]], dtype=int32)>

In [ ]:
t[1,2].assign(87)

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=int32, numpy=
array([[12, 25, 23, 16],
       [10, 35, 87,  7]], dtype=int32)>

In [ ]:
t[1,1].assign(35)

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=int32, numpy=
array([[12, 25, 23, 16],
       [10, 35,  5,  7]], dtype=int32)>

In [ ]:
t

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([35, 25, 23, 16], dtype=int32)>

In [ ]:
t[0].assign(21)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([21, 25, 23, 16], dtype=int32)>

In [ ]:
t

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([21, 25, 23, 16], dtype=int32)>


Now let's try to change a value in a tf.constant() tensor.

In [ ]:
tc = tf.constant([12,15,14,16])
tc

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12, 15, 14, 16], dtype=int32)>

Other ways to make tensors
Though you might rarely use these (remember, many tensor operations are done behind the scenes for you), you can use tf.ones() to create a tensor of all ones and tf.zeros() to create a tensor of all zeros.

In [ ]:
tf.zeros(shape = (2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# Make a tensor of all ones
tf.ones(shape=(5,2,3))

<tf.Tensor: shape=(5, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
# Make a tensor of all zeros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

Turn NumPy arrays in into tensors

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

## Getting information from tensors (shape, rank, size)

There will be times when you'll want to get different pieces of information from your tensors, in particular, you should know the following tensor vocabulary:

- Shape: The length (number of elements) of each of the dimensions of a tensor.
- Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
- Axis or Dimension: A particular dimension of a tensor.
- Size: The total number of items in the tensor.


You'll use these especially when you're trying to line up the shapes of your data to the shapes of your model.
For example, making sure the shape of your image tensors are the same shape as your models input layer.

In [ ]:
a = np.arange(1,25)
b = tf.constant(a, shape = (2,2,2,3))
b

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int64, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])>

In [ ]:
b.shape[0:2]

TensorShape([2, 2])

In [ ]:
b.ndim

4

In [ ]:
tf.size(b).numpy()

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
b[0,1:,1:3]

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 6,  7],
       [10, 11]])>

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.ndim, rank_4_tensor.shape

(4, TensorShape([2, 3, 4, 5]))

In [ ]:
a = tf.constant([1,2,3])
a.ndim, a.shape

(1, TensorShape([3]))

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor.shape[-1]

5

In [ ]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
tf.size(rank_4_tensor).numpy()

120

In [ ]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor = tf.Variable(np.arange(0,120,1))
# rank_4_tensor = tf.reshape(rank_4_tensor, shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Variable 'Variable:0' shape=(120,) dtype=int64, numpy=
array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])>

In [ ]:
tf.reshape(rank_4_tensor, shape = (3,4,2,5))

<tf.Tensor: shape=(3, 4, 2, 5), dtype=int64, numpy=
array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9]],

        [[ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29]],

        [[ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]]],


       [[[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69]],

        [[ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]]],


       [[[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89]],

        [[ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109]],

        [[110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])>

In [ ]:
a = tf.reshape(rank_4_tensor, shape = (12,10))
a

<tf.Tensor: shape=(12, 10), dtype=int64, numpy=
array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])>

In [ ]:
a = tf.reshape(a, shape = (2, 3, 4, 5))

In [ ]:
#shape
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
#rank
rank_4_tensor.ndim

4

In [ ]:
rank_4_tensor.shape[0:2]

TensorShape([2, 3])

In [ ]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
tf.size(rank_4_tensor).numpy()

120


You can also index tensors just like Python lists.

In [ ]:
l = [0,1,2,3,4,5,6]
l[0:3]

[0, 1, 2]

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
b

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int64, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])>

In [ ]:
b[1,0,1,1:]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([17, 18])>

In [ ]:
a[[0,2,0]]

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([40, 41, 42, 43, 44])>

In [ ]:
a

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int64, numpy=
array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])>

In [ ]:
rank_4_tensor[:1,1:2,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int64, numpy=array([[[[20, 21, 22, 23, 24]]]])>

In [ ]:
data = np.arange(120)
rank_4_tensor = tf.Variable(data)
rank_4_tensor = tf.reshape(rank_4_tensor, shape = (3,2,4,5))
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=int64, numpy=
array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]]],


       [[[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]]],


       [[[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])>

In [ ]:
rank_4_tensor[:2,:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 0,  1],
         [ 5,  6]],

        [[20, 21],
         [25, 26]]],


       [[[40, 41],
         [45, 46]],

        [[60, 61],
         [65, 66]]]])>

In [ ]:
rank_4_tensor[-2:, -2:, -2:, -2:]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 53,  54],
         [ 58,  59]],

        [[ 73,  74],
         [ 78,  79]]],


       [[[ 93,  94],
         [ 98,  99]],

        [[113, 114],
         [118, 119]]]])>

In [ ]:
rank_4_tensor.shape

TensorShape([3, 2, 4, 5])

In [ ]:
rank_4_tensor[1:,0:,2:,3:5]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 53,  54],
         [ 58,  59]],

        [[ 73,  74],
         [ 78,  79]]],


       [[[ 93,  94],
         [ 98,  99]],

        [[113, 114],
         [118, 119]]]])>

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 0,  1],
         [ 5,  6]],

        [[20, 21],
         [25, 26]]],


       [[[60, 61],
         [65, 66]],

        [[80, 81],
         [85, 86]]]])>

In [ ]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 0,  1],
         [ 5,  6]],

        [[20, 21],
         [25, 26]]],


       [[[60, 61],
         [65, 66]],

        [[80, 81],
         [85, 86]]]])>

In [ ]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int64, numpy=array([[[[0, 1, 2, 3, 4]]]])>

In [ ]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int64, numpy=
array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])>

In [ ]:
rank_4_tensor[:,:,:,-1]

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[  4,   9,  14,  19],
        [ 24,  29,  34,  39],
        [ 44,  49,  54,  59]],

       [[ 64,  69,  74,  79],
        [ 84,  89,  94,  99],
        [104, 109, 114, 119]]])>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

## Manipulating tensors (tensor operations)
Finding patterns in tensors (numerical representation of data) requires manipulating them.

Again, when building models in TensorFlow, much of this pattern discovery is done for you.

### Basic operations
You can perform many of the basic mathematical operations directly on tensors using Python operators such as, +, -, *.

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor * 10 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110,  80],
       [ 40,  50]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Use the tensorflow function equivalent of the '*' (multiply) operator
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>


### Matrix mutliplication

One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:

(3, 5) @ (3, 5) won't work

(5, 3) @ (3, 5) will work

(3, 5) @ (5, 3) will work

The resulting matrix has the shape of the outer dimensions:

(5, 3) @ (3, 5) -> (5, 5)

(3, 5) @ (5, 3) -> (3, 3)


Note: '@' in Python is the symbol for matrix multiplication.

In [ ]:
a = tf.constant([3,5,6,1], shape = (2,2))
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 1]], dtype=int32)>

In [ ]:
tf.matmul(a, a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[39, 20],
       [24, 31]], dtype=int32)>

In [ ]:
a @ a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[39, 20],
       [24, 31]], dtype=int32)>

In [ ]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>


Both of these examples work because our tensor variable is of shape (2, 2).

What if we created some tensors which had mismatched shapes?

In [ ]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrix multiply them (will error)
X @ Y

InvalidArgumentError: ignored

Trying to matrix multiply two tensors with the shape (3, 2) errors because the inner dimensions don't match.

We need to either:

Reshape X to (2, 3) so it's (2, 3) @ (3, 2).

Reshape Y to (3, 2) so it's (3, 2) @ (2, 3).

We can do this with either:

tf.reshape() - allows us to reshape a tensor into a defined shape.

tf.transpose() - switches the dimensions of a given tensor.
lining up dimensions for dot products

Let's try tf.reshape() first.

In [ ]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
X @ tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X.shape

TensorShape([3, 2])

In [ ]:
# Try matrix multiplication with reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

It worked, let's try the same with a reshaped X, except this time we'll use tf.transpose() and tf.matmul().

In [ ]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [ ]:
# Try matrix multiplication
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.matmul(a = X, b = Y, transpose_a=True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# You can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# You can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_b=True)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Notice the difference in the resulting shapes when tranposing X or reshaping Y.

This is because of the 2nd rule mentioned above:

- (3, 2) @ (2, 3) -> (3, 3) done with X @ tf.reshape(Y, shape=(2, 3))
- (2, 3) @ (3, 2) -> (2, 2) done with tf.matmul(tf.transpose(X), Y)

This kind of data manipulation is a reminder: you'll spend a lot of your time in machine learning and working with neural networks reshaping data (in the form of tensors) to prepare it to be used with various operations (such as feeding it to a model).

## The dot product
Multiplying matrices by each other is also referred to as the dot product.

You can perform the tf.matmul() operation using tf.tensordot().

In [ ]:
tf.tensordot(X, tf.transpose(Y), axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform the dot product on X and Y (requires X to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

You might notice that although using both reshape and tranpose work, you get different results when using each.

Let's see an example, first with tf.transpose() then with tf.reshape().

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
import tensorflow as tf

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>


calling tf.reshape() and tf.transpose() on Y don't necessarily result in the same values.

In [ ]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


So which should you use?

Again, most of the time these operations (when they need to be run, such as during the training a neural network, will be implemented for you).

But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.

Matrix multiplication tidbits
If we transposed Y, it would be represented as
Y
T
 (note the capital T for tranpose).
Get an illustrative view of matrix multiplication by [Math is Fun](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

Try a hands-on demo of matrix multiplcation: http://matrixmultiplication.xyz/

### Changing the datatype of a tensor

You can change the datatype of a tensor using tf.cast().

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [ ]:
tf.cast(B, dtype = tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>


### Getting the absolute value
Sometimes you'll want the absolute values (all values are positive) of elements in your tensors.

To do so, you can use tf.abs().

In [ ]:
a = -5
a

-5

In [ ]:
abs(a)

5

In [ ]:
# Create tensor with negative values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>


### Finding the min, max, mean, sum (aggregation)

- tf.reduce_min() - find the minimum value in a tensor.

- tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).

- tf.reduce_mean() - find the mean of all elements in a tensor.

- tf.reduce_sum() - find the sum of all elements in a tensor.

Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

In [ ]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=20))
E

<tf.Tensor: shape=(20,), dtype=int64, numpy=
array([ 3, 63, 22,  9, 45, 93, 48, 55, 42, 37, 99, 17, 68,  5, 96, 73, 11,
       79, 43, 30])>

In [ ]:
tf.reduce_sum(E).numpy()

938

In [ ]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [ ]:
# Find the minimum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2830>


You can also find the standard deviation (tf.reduce_std()) and variance (tf.reduce_variance()) of elements in a tensor using similar methods.

### Finding the positional maximum and minimum
How about finding the position a tensor where the maximum value occurs?

This is helpful when you want to line up your labels (say ['Green', 'Blue', 'Red']) with your prediction probabilities tensor (e.g. [0.98, 0.01, 0.01]).

In this case, the predicted label (the one with the highest prediction probability) would be 'Green'.

You can do the same for the minimum (if required) with the following:

 - tf.argmax() - find the position of the maximum element in a given tensor.
 - tf.argmin() - find the position of the minimum element in a given tensor.

In [ ]:
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.54270445, 0.844515  , 0.17818898, 0.04219552, 0.31169326,
       0.7101041 , 0.79124302, 0.50921268, 0.86163199, 0.69527058,
       0.33902492, 0.44292398, 0.96139969, 0.11188036, 0.66844405,
       0.72933243, 0.38031866, 0.94104794, 0.06975655, 0.28839483,
       0.2767401 , 0.08013489, 0.24422739, 0.18889591, 0.60643709,
       0.57652388, 0.16848384, 0.80885131, 0.5482614 , 0.70926914,
       0.75316356, 0.00128511, 0.73886119, 0.41111622, 0.73658299,
       0.3362474 , 0.12765   , 0.67990336, 0.95639581, 0.86907021,
       0.27434667, 0.97850141, 0.18119687, 0.6279654 , 0.70268791,
       0.71542893, 0.02624157, 0.8038085 , 0.48354543, 0.99115969])>

In [ ]:
label = ["Green", "Blue", "Yellow"]
output_prob = tf.constant(np.random.random(3))
output_prob

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.5063575 , 0.57761709, 0.11946823])>

In [ ]:
tf.argmax(output_prob)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
label[tf.argmax(output_prob)]

'Blue'

In [ ]:
# Find the maximum element position of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=31>

In [ ]:
F[49]

<tf.Tensor: shape=(), dtype=float64, numpy=0.9911596864097134>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.0012851132941605892>

In [ ]:
id = tf.argmax(F).numpy()
F[id].numpy()

0.9988429420127982

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9988429420127982>

In [ ]:
id

16

In [ ]:
# Find the minimum element position of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [ ]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 16
The maximum value of F is: 0.9988429420127982
Using tf.argmax() to index F, the maximum value of F is: 0.9988429420127982
Are the two max values the same (they should be)? True
